# == Schema Information
# Schema version: 20100609172527
#
# Table name: steps
#
#  id            :integer(4)      not null, primary key
#  description   :text
#  title         :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  experiment_id :integer(4)
#  step_order    :integer(4)
#  autogenerated :boolean(1)
#

class Step < ActiveRecord::Base
  attr_accessible :title, :description, :image, :experiment_id,
                  :step_order, :autogenerated
  belongs_to :experiment
  has_one :image
#  image_id      :integer(4)
#
end
